[package]
name = "serde_json_lodash"
version = "0.2.0"
authors = ["up9cloud <8325632+up9cloud@users.noreply.github.com>"]
description = "lodash.js ported version, work with serde_json::Value"
keywords = ["serde", "serde_json", "json", "lodash"]
license = "MIT"
edition = "2024"

[features]
default = ["camel"]
all = ["camel", "lazy_static"]
camel = []

[dependencies]
serde_json = "1"
paste = "1"
lazy_static = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.3"

[lib]
bench = false

[[bench]]
name = "criterion"
harness = false
