on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    needs: [check]
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
  publish:
    needs: [test]
    name: Publish to cargo.rs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      # - uses: actions-rs/cargo@v1
      #   if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      #   with:
      #     command: build
      #     args: --release --all-features
      - uses: actions-rs/cargo@v1
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        with:
          command: login
          args: ${{secrets.CRATES_IO_TOKEN}}
      - uses: actions-rs/cargo@v1
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        with:
          command: publish
  notify:
    if: cancelled() == false
    needs:
      - check
      - test
      - publish
    runs-on: ubuntu-latest
    steps:
      - id: set_status
        run: |
          if [ "${{needs.check.result}}" = "success" ] &&
            [ "${{needs.test.result}}" = "success" ] &&
            [ "${{needs.publish.result}}" = "success" ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
            exit 2
          fi
      - uses: up9cloud/action-notify@master
        if: cancelled() == false
        env:
          GITHUB_JOB_STATUS: ${{steps.set_status.outputs.status}}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
